#############################################################################
# Makefile for building: QCanObserver
# Generated by qmake (2.01a) (Qt 4.5.1) on: Fri Nov 27 17:30:24 2009
# Project:  QCanObserver.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QCanObserver.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I/usr/include/qwt5 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -L/usr/lib/ -lqwt -lpcan -lQtXml -L/usr/lib/qt4 -pthread -pthread -lQtGui -L/usr/X11R6/lib -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lXrandr -lXinerama -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		readthread.cpp \
		DevDialog.cpp \
		candevice.cpp \
		errordialog.cpp \
		messagebufferinterface.cpp \
		stringlistmodel.cpp \
		FilterDialog.cpp \
		filterdef.cpp \
		graphicwindow.cpp \
		processdatabase.cpp \
		calrule.cpp \
		candataitemselector.cpp moc_mainwindow.cpp \
		moc_readthread.cpp \
		moc_DevDialog.cpp \
		moc_errordialog.cpp \
		moc_messagebufferinterface.cpp \
		moc_stringlistmodel.cpp \
		moc_FilterDialog.cpp \
		moc_filterdef.cpp \
		moc_graphicwindow.cpp \
		moc_candataitemselector.cpp
OBJECTS       = main.o \
		mainwindow.o \
		readthread.o \
		DevDialog.o \
		candevice.o \
		errordialog.o \
		messagebufferinterface.o \
		stringlistmodel.o \
		FilterDialog.o \
		filterdef.o \
		graphicwindow.o \
		processdatabase.o \
		calrule.o \
		candataitemselector.o \
		moc_mainwindow.o \
		moc_readthread.o \
		moc_DevDialog.o \
		moc_errordialog.o \
		moc_messagebufferinterface.o \
		moc_stringlistmodel.o \
		moc_FilterDialog.o \
		moc_filterdef.o \
		moc_graphicwindow.o \
		moc_candataitemselector.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QCanObserver.pro
QMAKE_TARGET  = QCanObserver
DESTDIR       = 
TARGET        = QCanObserver

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_DevDialog.h ui_errordialog.h ui_FilterDialog.h ui_filterdef.h ui_graphicwindow.h ui_candataitemselector.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QCanObserver.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt4/libQtXml.prl \
		/usr/lib/qt4/libQtCore.prl \
		/usr/lib/qt4/libQtGui.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QCanObserver.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/qt4/libQtXml.prl:
/usr/lib/qt4/libQtCore.prl:
/usr/lib/qt4/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile QCanObserver.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QCanObserver1.0.0 || $(MKDIR) .tmp/QCanObserver1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QCanObserver1.0.0/ && $(COPY_FILE) --parents mainwindow.h readthread.h DevDialog.h candevice.h errordialog.h messagebufferinterface.h stringlistmodel.h FilterDialog.h filterdef.h graphicwindow.h processdatabase.h calrule.h candataitemselector.h .tmp/QCanObserver1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp readthread.cpp DevDialog.cpp candevice.cpp errordialog.cpp messagebufferinterface.cpp stringlistmodel.cpp FilterDialog.cpp filterdef.cpp graphicwindow.cpp processdatabase.cpp calrule.cpp candataitemselector.cpp .tmp/QCanObserver1.0.0/ && $(COPY_FILE) --parents mainwindow.ui DevDialog.ui errordialog.ui FilterDialog.ui FilterDialog.ui filterdef.ui filterdef.ui graphicwindow.ui candataitemselector.ui .tmp/QCanObserver1.0.0/ && (cd `dirname .tmp/QCanObserver1.0.0` && $(TAR) QCanObserver1.0.0.tar QCanObserver1.0.0 && $(COMPRESS) QCanObserver1.0.0.tar) && $(MOVE) `dirname .tmp/QCanObserver1.0.0`/QCanObserver1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QCanObserver1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_readthread.cpp moc_DevDialog.cpp moc_errordialog.cpp moc_messagebufferinterface.cpp moc_stringlistmodel.cpp moc_FilterDialog.cpp moc_filterdef.cpp moc_graphicwindow.cpp moc_candataitemselector.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_readthread.cpp moc_DevDialog.cpp moc_errordialog.cpp moc_messagebufferinterface.cpp moc_stringlistmodel.cpp moc_FilterDialog.cpp moc_filterdef.cpp moc_graphicwindow.cpp moc_candataitemselector.cpp
moc_mainwindow.cpp: readthread.h \
		candevice.h \
		messagebufferinterface.h \
		FilterDialog.h \
		filterdef.h \
		DevDialog.h \
		stringlistmodel.h \
		graphicwindow.h \
		processdatabase.h \
		calrule.h \
		candataitemselector.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_readthread.cpp: candevice.h \
		messagebufferinterface.h \
		FilterDialog.h \
		filterdef.h \
		readthread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) readthread.h -o moc_readthread.cpp

moc_DevDialog.cpp: DevDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) DevDialog.h -o moc_DevDialog.cpp

moc_errordialog.cpp: errordialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) errordialog.h -o moc_errordialog.cpp

moc_messagebufferinterface.cpp: messagebufferinterface.h
	/usr/bin/moc $(DEFINES) $(INCPATH) messagebufferinterface.h -o moc_messagebufferinterface.cpp

moc_stringlistmodel.cpp: stringlistmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) stringlistmodel.h -o moc_stringlistmodel.cpp

moc_FilterDialog.cpp: filterdef.h \
		FilterDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) FilterDialog.h -o moc_FilterDialog.cpp

moc_filterdef.cpp: filterdef.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filterdef.h -o moc_filterdef.cpp

moc_graphicwindow.cpp: messagebufferinterface.h \
		processdatabase.h \
		calrule.h \
		candataitemselector.h \
		graphicwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) graphicwindow.h -o moc_graphicwindow.cpp

moc_candataitemselector.cpp: processdatabase.h \
		calrule.h \
		candataitemselector.h
	/usr/bin/moc $(DEFINES) $(INCPATH) candataitemselector.h -o moc_candataitemselector.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_DevDialog.h ui_errordialog.h ui_FilterDialog.h ui_FilterDialog.h ui_filterdef.h ui_filterdef.h ui_graphicwindow.h ui_candataitemselector.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_DevDialog.h ui_errordialog.h ui_FilterDialog.h ui_FilterDialog.h ui_filterdef.h ui_filterdef.h ui_graphicwindow.h ui_candataitemselector.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_DevDialog.h: DevDialog.ui
	/usr/bin/uic DevDialog.ui -o ui_DevDialog.h

ui_errordialog.h: errordialog.ui
	/usr/bin/uic errordialog.ui -o ui_errordialog.h

ui_FilterDialog.h: FilterDialog.ui
	/usr/bin/uic FilterDialog.ui -o ui_FilterDialog.h

ui_FilterDialog.h: FilterDialog.ui
	/usr/bin/uic FilterDialog.ui -o ui_FilterDialog.h

ui_filterdef.h: filterdef.ui
	/usr/bin/uic filterdef.ui -o ui_filterdef.h

ui_filterdef.h: filterdef.ui
	/usr/bin/uic filterdef.ui -o ui_filterdef.h

ui_graphicwindow.h: graphicwindow.ui
	/usr/bin/uic graphicwindow.ui -o ui_graphicwindow.h

ui_candataitemselector.h: candataitemselector.ui
	/usr/bin/uic candataitemselector.ui -o ui_candataitemselector.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		readthread.h \
		candevice.h \
		messagebufferinterface.h \
		FilterDialog.h \
		filterdef.h \
		DevDialog.h \
		stringlistmodel.h \
		graphicwindow.h \
		processdatabase.h \
		calrule.h \
		candataitemselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		readthread.h \
		candevice.h \
		messagebufferinterface.h \
		FilterDialog.h \
		filterdef.h \
		DevDialog.h \
		stringlistmodel.h \
		graphicwindow.h \
		processdatabase.h \
		calrule.h \
		candataitemselector.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

readthread.o: readthread.cpp readthread.h \
		candevice.h \
		messagebufferinterface.h \
		FilterDialog.h \
		filterdef.h \
		errordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readthread.o readthread.cpp

DevDialog.o: DevDialog.cpp DevDialog.h \
		ui_DevDialog.h \
		candevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DevDialog.o DevDialog.cpp

candevice.o: candevice.cpp candevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o candevice.o candevice.cpp

errordialog.o: errordialog.cpp errordialog.h \
		ui_errordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errordialog.o errordialog.cpp

messagebufferinterface.o: messagebufferinterface.cpp messagebufferinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o messagebufferinterface.o messagebufferinterface.cpp

stringlistmodel.o: stringlistmodel.cpp stringlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringlistmodel.o stringlistmodel.cpp

FilterDialog.o: FilterDialog.cpp FilterDialog.h \
		filterdef.h \
		ui_FilterDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FilterDialog.o FilterDialog.cpp

filterdef.o: filterdef.cpp filterdef.h \
		ui_filterdef.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterdef.o filterdef.cpp

graphicwindow.o: graphicwindow.cpp graphicwindow.h \
		messagebufferinterface.h \
		processdatabase.h \
		calrule.h \
		candataitemselector.h \
		ui_graphicwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicwindow.o graphicwindow.cpp

processdatabase.o: processdatabase.cpp processdatabase.h \
		calrule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o processdatabase.o processdatabase.cpp

calrule.o: calrule.cpp calrule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calrule.o calrule.cpp

candataitemselector.o: candataitemselector.cpp candataitemselector.h \
		processdatabase.h \
		calrule.h \
		ui_candataitemselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o candataitemselector.o candataitemselector.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_readthread.o: moc_readthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_readthread.o moc_readthread.cpp

moc_DevDialog.o: moc_DevDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DevDialog.o moc_DevDialog.cpp

moc_errordialog.o: moc_errordialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errordialog.o moc_errordialog.cpp

moc_messagebufferinterface.o: moc_messagebufferinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_messagebufferinterface.o moc_messagebufferinterface.cpp

moc_stringlistmodel.o: moc_stringlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stringlistmodel.o moc_stringlistmodel.cpp

moc_FilterDialog.o: moc_FilterDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FilterDialog.o moc_FilterDialog.cpp

moc_filterdef.o: moc_filterdef.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filterdef.o moc_filterdef.cpp

moc_graphicwindow.o: moc_graphicwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicwindow.o moc_graphicwindow.cpp

moc_candataitemselector.o: moc_candataitemselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_candataitemselector.o moc_candataitemselector.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

